### ISSUE TITLE
Both Prod 1.0 and Staging are broken.  Both return "TypeError: Cannot call method "map" of undefined.

### ISSUE THREAD

**Issue by marksmcsar** [smcsar/duty-officer-addon#11]
![image](https://cloud.githubusercontent.com/assets/6392088/10503914/ad2de5f4-72af-11e5-8da7-d02f1c4b2db2.png)

**Comment by andrew-nguyen** [comment]
@marksmcsar Was this a transient error?  It sounds like you were able to use it last night and I just tried it again this morning and both the 1.0 and staging versions appear to work.

**Comment by marksmcsar** [comment]
It worked this morning.  I had not tried it since I reported the bug.  I 
would close it for now.  I'll open a new one if it happens again.

On 10/21/2015 07:06, Andrew Nguyen wrote:

> @marksmcsar https://github.com/marksmcsar Was this a transient 
> error? It sounds like you were able to use it last night and I just 
> tried it again this morning and both the 1.0 and staging versions 
> appear to work.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/smcsar/duty-officer-addon/issues/11#issuecomment-149906717.

## 

Mark Lowpensky - mark.lowpensky@sanmateosar.org
650-293-9163 - Administrative & Technology Section Chief
Search and Rescue Unit - San Mateo County Sheriff's Office
www.sanmateosar.org
