### ISSUE TITLE
Freeze the top two rows the of the spreadsheet

### ISSUE THREAD

**Issue by marksmcsar** [smcsar/duty-officer-addon#4]
It would be nice to freeze the top two rows of the spreadsheet so that they are always visible.

**Comment by andrew-nguyen** [comment]
@sjgarcia Can you add a link to the API docs for freezing the panes to this issue?  Thanks.

**Comment by sjgarcia** [comment]
"Access and modify spreadsheet sheets. Common operations are renaming a sheet and accessing range objects from the sheet."
https://developers.google.com/apps-script/reference/spreadsheet/sheet

**Comment by marksmcsar** [comment]
Don't we want this:
|setFrozenRows(rows) 
https://developers.google.com/apps-script/reference/spreadsheet/sheet#setFrozenRows%28Integer%29| 
    |void|  Freezes the given number of rows.

On 9/29/2015 11:40, sjgarcia wrote:

> "Access and modify spreadsheet sheets. Common operations are renaming 
> a sheet and accessing range objects from the sheet."
> https://developers.google.com/apps-script/reference/spreadsheet/sheet
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/smcsar/duty-officer-addon/issues/4#issuecomment-144151151.

## 

Mark Lowpensky - mark.lowpensky@sanmateosar.org
650-293-9163 - Administrative & Technology Section Chief
Search and Rescue Unit - San Mateo County Sheriff's Office
www.sanmateosar.org

**Comment by sjgarcia** [comment]
Yes.  Andy asked for a link to the API and I felt the larger doc with all the sheet relevent methods would be more useful.  In retrospect, perhaps he wanted the specific method?

Steve

**Comment by andrew-nguyen** [comment]
Merged into dev
